/**
 * Build Google Apps Script HTML Service files from the static site sources.
 *
 * Usage: node scripts/build-gas.mjs
 *
 * Writes into gas/:
 *   Index.html, Styles.html, Data.html, Schedules.html, Events.html, Clock.html
 *
 * Code.gs and appsscript.json are maintained by hand in gas/.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const GAS = path.join(ROOT, "gas");

function read(rel) {
  return fs.readFileSync(path.join(ROOT, rel), "utf8");
}

function write(rel, contents) {
  const dest = path.join(GAS, rel);
  fs.writeFileSync(dest, contents);
  console.log(`wrote gas/${rel} (${contents.length} bytes)`);
}

function stripModuleExports(source) {
  return source
    .replace(/^export\s+async\s+function\s+/gm, "async function ")
    .replace(/^export\s+function\s+/gm, "function ")
    .replace(/^export\s+const\s+/gm, "const ")
    .replace(/^export\s+\{[^}]+\};?\s*$/gm, "");
}

function stripImports(source) {
  return source.replace(/^import\s+[\s\S]*?from\s+["'][^"']+["'];?\s*$/gm, "");
}

function buildDataHtml() {
  const schedule = read("js/schedule-data.json");
  const events = read("js/events-data.json");
  return `<!-- Generated by scripts/build-gas.mjs — do not edit by hand -->
<script>
window.__SCHEDULE_DATA__ = ${schedule};
window.__EVENTS_DATA__ = ${events};
</script>
`;
}

function buildSchedulesHtml() {
  let src = stripModuleExports(read("js/schedules.js"));

  // Prefer embedded data when running under Apps Script HtmlService.
  src = src.replace(
    /export async function loadScheduleData\(\) \{[\s\S]*?\n\}/,
    "" // already stripped export; replace the function body below
  );
  src = src.replace(
    /async function loadScheduleData\(\) \{[\s\S]*?\n\}/,
    `async function loadScheduleData() {
  if (typeof window !== "undefined" && window.__SCHEDULE_DATA__) {
    return window.__SCHEDULE_DATA__;
  }
  throw new Error("Schedule data missing (rebuild gas with scripts/build-gas.mjs)");
}`
  );

  const exports = [
    "loadScheduleData",
    "getPeriodStatus",
    "formatDuration",
    "getSavedOverride",
    "setSavedOverride",
    "getSavedLunch",
    "setSavedLunch",
    "getSavedClockDelay",
    "setSavedClockDelay",
    "getSavedThemePrimary",
    "setSavedThemePrimary",
    "getSavedThemeSecondary",
    "setSavedThemeSecondary",
    "getAdjustedNow",
    "getOneprideSignupReminder",
    "chicagoDateString",
    "resolveScheduleId",
    "getScheduleById",
    "getDayTimeline",
    "getActiveTimelineId",
    "getPassingSummary",
    "formatHHMM",
    "DEFAULT_THEME_PRIMARY",
    "DEFAULT_THEME_SECONDARY",
  ];

  return `<!-- Generated by scripts/build-gas.mjs — do not edit by hand -->
<script>
(() => {
${src}

window.LHSSchedules = {
${exports.map((n) => `  ${n},`).join("\n")}
};
})();
</script>
`;
}

function buildEventsHtml() {
  let src = stripImports(stripModuleExports(read("js/events.js")));

  // Use schedules helpers from the global namespace.
  src =
    `const { chicagoDateString, formatHHMM } = window.LHSSchedules;\n\n` +
    src;

  // Replace live fetch + month HTML proxy with one Apps Script round-trip
  // that returns already-parsed event objects (see gas/Code.gs).
  src = src.replace(
    /async function fetchMonthHtml\(dateYmd\) \{[\s\S]*?\n\}/,
    `function gasRun(fnName, ...args) {
  return new Promise((resolve, reject) => {
    if (typeof google === "undefined" || !google.script || !google.script.run) {
      reject(new Error("google.script.run unavailable"));
      return;
    }
    google.script.run
      .withSuccessHandler(resolve)
      .withFailureHandler((err) => {
        const msg =
          (err && (err.message || err.details || err.name)) || String(err);
        reject(new Error(msg));
      })[fnName](...args);
  });
}`
  );

  src = src.replace(
    /async function fetchLiveEvents\(now = new Date\(\)\) \{[\s\S]*?\n\}/,
    `async function fetchLiveEvents(now = new Date()) {
  const today = chicagoDateString(now);
  let cursor = firstOfMonth(today);
  const months = [];
  for (let i = 0; i <= MONTHS_AHEAD; i++) {
    months.push(cursor);
    cursor = nextMonthStart(cursor);
  }
  const events = await gasRun("fetchLhsCalendarEvents", months);
  return { events: events || [], live: true };
}`
  );

  src = src.replace(
    /async function loadCachedEventsData\(\) \{[\s\S]*?\n\}/,
    `async function loadCachedEventsData() {
  if (typeof window !== "undefined" && window.__EVENTS_DATA__) {
    return window.__EVENTS_DATA__;
  }
  throw new Error("Cached events missing (rebuild gas with scripts/build-gas.mjs)");
}`
  );

  const exports = [
    "fetchLiveEvents",
    "loadCachedEventsData",
    "mergeScheduleEvents",
    "getVisibleEvents",
    "CALENDAR_PAGE",
    "parseCalendarHtml",
    "loadEventsData",
    "buildEventList",
  ];

  return `<!-- Generated by scripts/build-gas.mjs — do not edit by hand -->
<script>
(() => {
${src}

window.LHSEvents = {
${exports.map((n) => `  ${n},`).join("\n")}
};
})();
</script>
`;
}

function buildClockHtml() {
  let src = stripImports(read("js/clock.js"));

  const preamble = `const {
  loadScheduleData,
  getPeriodStatus,
  formatDuration,
  getSavedOverride,
  setSavedOverride,
  getSavedLunch,
  setSavedLunch,
  getSavedClockDelay,
  setSavedClockDelay,
  getSavedThemePrimary,
  setSavedThemePrimary,
  getSavedThemeSecondary,
  setSavedThemeSecondary,
  getAdjustedNow,
  getOneprideSignupReminder,
  chicagoDateString,
  resolveScheduleId,
  getScheduleById,
  getDayTimeline,
  getActiveTimelineId,
  getPassingSummary,
  formatHHMM,
} = window.LHSSchedules;

const {
  fetchLiveEvents,
  loadCachedEventsData,
  mergeScheduleEvents,
  getVisibleEvents,
  CALENDAR_PAGE,
} = window.LHSEvents;
`;

  // Soften the Netlify-oriented error / status copy for Apps Script.
  src = src.replace(
    /"Cached events \(run node scripts\/serve\.mjs for live school calendar\)"/,
    '"Cached events — run testCalendar in the Apps Script editor to authorize live calendar"'
  );
  src = src.replace(
    /"Could not load schedule data\. Run: node scripts\/serve\.mjs — then open http:\/\/localhost:8080"/,
    '"Could not load schedule data. Redeploy the Apps Script web app after rebuilding gas/."'
  );

  return `<!-- Generated by scripts/build-gas.mjs — do not edit by hand -->
<script>
(() => {
${preamble}
${src}
})();
</script>
`;
}

function buildStylesHtml() {
  const css = read("styles.css");
  return `<!-- Generated by scripts/build-gas.mjs — do not edit by hand -->
<style>
${css}
</style>
`;
}

function buildIndexHtml() {
  const html = read("index.html");

  // Drop external stylesheet + module script; inject Apps Script includes instead.
  let out = html
    .replace(
      /<head>/,
      `<head>\n    <base target="_top" />`
    )
    .replace(
      /\s*<link rel="stylesheet" href="styles\.css" \/>\s*/,
      "\n    <?!= include('Styles'); ?>\n"
    )
    .replace(
      /\s*<script type="module" src="js\/clock\.js"><\/script>\s*/,
      `
    <?!= include('Data'); ?>
    <?!= include('Schedules'); ?>
    <?!= include('Events'); ?>
    <?!= include('Clock'); ?>
`
    );

  // HtmlService already sets charset/viewport via evaluate(); keep tags for clarity.
  return `<!-- Generated by scripts/build-gas.mjs — do not edit by hand -->
${out}`;
}

function main() {
  fs.mkdirSync(GAS, { recursive: true });
  write("Styles.html", buildStylesHtml());
  write("Data.html", buildDataHtml());
  write("Schedules.html", buildSchedulesHtml());
  write("Events.html", buildEventsHtml());
  write("Clock.html", buildClockHtml());
  write("Index.html", buildIndexHtml());
  console.log("Google Apps Script bundle ready in gas/");

  // Also build the sendable "LHSCD Appscript" zip (2-file import package)
  execFileSync(process.execPath, [path.join(__dirname, "build-lhscd-appscript.mjs")], {
    cwd: ROOT,
    stdio: "inherit",
  });
}

main();
